name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: "10.2"
softdepend: [KnokkoCore, CrazyEnchantments, ActionBarAPI, Mimic, ItemBridge, WorldGuard]
loadbefore: [UltraChest]
commands:
  customitems:
    description: Commands for the CustomItems plugin
    usage: /kci give/take/list/damage/repair/debug/setblock/encode/reload
    aliases: [ci, kci]
