name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: "9.22"
softdepend: [KnokkoCore, CrazyEnchantments, ActionBarAPI, Mimic, ItemBridge]
loadbefore: [UltraChest]
commands:
  customitems:
    description: Commands for the CustomItems plugin
    usage: /kci give/take/list/damage/repair/debug/setblock/encode/reload
    aliases: [ci, kci]
