name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: 9.11
depend: [KnokkoCore]
softdepend: [CrazyEnchantments, ActionBarAPI]
loadbefore: [UltraChest]
commands:
  customitems:
    description: Commands for the CustomItems plugin
    usage: /kci give <item> [player] or /kci list or /kci reload or /kci debug or /kci repair <amount> [player] /kci damage <amount> [player] or /kci setblock <block> [x] [y] [z] [world]
    aliases: [ci, kci]
